run_dir: ./output/pendulum_state/${now:%Y-%m-%d}/${now:%H-%M-%S}

wandb_enabled: False
wandb_entity: null
wandb_project: pendulum_rinn

load_lyaloss: null
Vmin_x_pgd_path: null
derivative_x_buffer_path: null 
